services:
  - type: web
    name: sync-chat-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        fromEnv: MONGO_URI
      - key: PORT
        value: 10000
